# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules =
    [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/12f77533-8736-48f3-bb13-ec75621fd0cf";
    fsType = "ext4";
  };

  fileSystems."/mnt/mint" = {
    device = "/dev/disk/by-uuid/81503bb0-48b0-486a-8890-266628de3419";
    fsType = "btrfs";
  };

  fileSystems."/mnt/win" = {
    device = "/dev/disk/by-uuid/66E2FB4FE2FB224B";
    fsType = "ntfs";
  };

  fileSystems."/mnt/shit" = {
    device = "/dev/disk/by-uuid/DCFE4455FE4429DA";
    fsType = "ntfs";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/2D51-9331";
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];
  };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp4s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode =
    lib.mkDefault config.hardware.enableRedistributableFirmware;
}
